# Generated by Django 4.0.3 on 2022-10-08 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('necktie_doctor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='doctor',
        ),
        migrations.AddField(
            model_name='doctor',
            name='education',
            field=models.CharField(default=None, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='language',
            field=models.CharField(default=None, max_length=150),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Communication',
        ),
        migrations.DeleteModel(
            name='Education',
        ),
    ]
